apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-ds
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: 15s

  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo-ds
          matcherRegex: "(?:traceID|trace_id)=(?P<traceId>[A-Fa-f0-9-]+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    uid: tempo-ds
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki-ds
        filterBySpanID: true
        filterByTraceID: true
        mapTagNamesEnabled: true
        tags:
          - key: service.name
            value: service_name
      serviceMap:
        datasourceUid: prometheus-ds
      search:
        hide: false
      nodeGraph:
        enabled: true
      spansToMetrics:
        datasourceUid: prometheus-ds
