global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: worker
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8001"]

  - job_name: watcher
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8002"]
